import propertyFormModel from "./propertyFormModel";
const {
  formField: {
    nickName,
    address,
    link,
    price,
    mortgage,
    lawn,
    vacancy,
    capX,
    repairs,
    insurance,
    tax,
    hoa,
    rentalIncome,
    downPay,
    closing,
    rehab,
  },
} = propertyFormModel;

export default {
  [nickName.name]: "Property 1",
  [address.name]: "11922 Your address, Tamp, florida, 22345",
  [link.name]: "https://material-ui.com/components/typography/",
  [price.name]: "200000",
  [mortgage.name]: "672",
  [lawn.name]: "0",
  [vacancy.name]: "95",
  [capX.name]: "100",
  [repairs.name]: "100",
  [insurance.name]: "67",
  [tax.name]: "170",
  [hoa.name]: "0",
  [rentalIncome.name]: "1900",
  [downPay.name]: "40000",
  [closing.name]: "1200",
  [rehab.name]: "5000",
};
